name: "Pull Request Labeler v2"
on:
- pull_request

jobs:
  labeler:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
    - uses: actions/labeler@v5
